### ISSUE TITLE
FizzBuzz 구현

### ISSUE THREAD

**Issue by s861m1** [UpstageAiLab5Group5/team_fizzbuzz#1]
## Description

fizzbuzz를 기능 구현을 위한 함수를 작성하세요.

## Tasks
- [ ] fizz
- [ ] buzz
- [ ] fizzbuzz

## References
https://en.wikipedia.org/wiki/Fizz_buzz

**Comment by tjdwlek0** [comment]
시작해주세요! 확인했습니다

**Comment by s861m1** [comment]
> 시작해주세요! 확인했습니다

넵!!
