### ISSUE TITLE
Fizzbuzz 구현

### ISSUE THREAD

**Issue by bluephysi01** [UpstageAiLab5Group5/team_fizzbuzz#2]
## Description

fizzbuzz를 기능 구현을 위한 함수를 작성하세요.
if , for 구문으로 구현하겠습니다.

## Tasks
- [x] fizz
- [x] buzz
- [x] fizzbuzz

**Comment by tjdwlek0** [comment]
감사합니다! 시작해주세요

**Comment by bluephysi01** [comment]
네~ 수고많으시네요~
